variable "er_peering_location" {
  type        = map(any)
  description = "ExpressRoute Locations"
  default = {
    "Amsterdam" : "Amsterdam"
    "Amsterdam2" : "Amsterdam2"
    "AsiaSouthEastSIN22Skytap" : "AsiaSouthEastSIN22 Skytap"
    "Atlanta" : "Atlanta"
    "Auckland" : "Auckland"
    "Bangkok" : "Bangkok"
    "Berlin" : "Berlin"
    "Bogota" : "Bogota"
    "Busan" : "Busan"
    "Campinas" : "Campinas"
    "Canberra" : "Canberra"
    "Canberra2" : "Canberra2"
    "CapeTown" : "CapeTown"
    "Chennai" : "Chennai"
    "Chennai2" : "Chennai2"
    "Chicago" : "Chicago"
    "Copenhagen" : "Copenhagen"
    "Dallas" : "Dallas"
    "Denver" : "Denver"
    "Dubai" : "Dubai"
    "Dubai2" : "Dubai2"
    "Dublin" : "Dublin"
    "Dublin2" : "Dublin2"
    "EastAsiaHKG20Skytap" : "EastAsiaHKG20 Skytap"
    "Frankfurt" : "Frankfurt"
    "Frankfurt2" : "Frankfurt2"
    "Geneva" : "Geneva"
    "HongKong" : "Hong Kong"
    "HongKong2" : "Hong Kong2"
    "Jakarta" : "Jakarta"
    "Jamnagar" : "Jamnagar"
    "Johannesburg" : "Johannesburg"
    "KualaLumpur" : "KualaLumpur"
    "LasVegas" : "Las Vegas"
    "London" : "London"
    "London2" : "London2"
    "LosAngeles" : "Los Angeles"
    "LosAngeles2" : "Los Angeles2"
    "Madrid" : "Madrid"
    "Marseille" : "Marseille"
    "Melbourne" : "Melbourne"
    "Miami" : "Miami"
    "Milan" : "Milan"
    "Minneapolis" : "Minneapolis"
    "Montreal" : "Montreal"
    "Mumbai" : "Mumbai"
    "Mumbai2" : "Mumbai2"
    "Mumbai3" : "Mumbai3"
    "Munich" : "Munich"
    "Nagpur" : "Nagpur"
    "NewYork" : "NewYork"
    "Newport" : "Newport"
    "Osaka" : "Osaka"
    "Oslo" : "Oslo"
    "Paris" : "Paris"
    "Perth" : "Perth"
    "Phoenix" : "Phoenix"
    "QuebecCity" : "Quebec City"
    "Queretaro" : "Queretaro"
    "RiodeJaneiro" : "Rio de Janeiro"
    "SanAntonio" : "San Antonio"
    "SaoPaulo" : "Sao Paulo"
    "Seattle" : "Seattle"
    "Seoul" : "Seoul"
    "SiliconValley" : "Silicon Valley"
    "SiliconValley2" : "Silicon Valley2"
    "Singapore" : "Singapore"
    "Singapore2" : "Singapore2"
    "SouthCentralUSSAT09Skytap" : "SouthCentralUSSAT09 Skytap"
    "Stavanger" : "Stavanger"
    "Stockholm" : "Stockholm"
    "Sydney" : "Sydney"
    "Sydney2" : "Sydney2"
    "Taipei" : "Taipei"
    "Tokyo" : "Tokyo"
    "Tokyo2" : "Tokyo2"
    "Toronto" : "Toronto"
    "UkSouthLON23Skytap" : "UkSouthLON23 Skytap"
    "UkSouthLON24Skytap" : "UkSouthLON24 Skytap"
    "Vancouver" : "Vancouver"
    "WashingtonDC" : "Washington DC"
    "WashingtonDC2" : "Washington DC2"
    "WestEuropeAMS23Skytap" : "WestEuropeAMS23 Skytap"
    "Zurich" : "Zurich"
  }
}
